<h1>Db2 Magic Query into Pandas Data Frame</h1>

<p><strong>Welcome!</strong> This notebook will provide examples of using Db2 Magic Commands and converting the out put to a Pandas Data Frame.  Many of our data science examples use data in a Pandas data frame, so I thogut that this example would be useful since the magic commands put the output of a query into a LIST data type.</p>

<h2 id="dataset">About Db2 Magic Commands</h2>

Db2 Magic commands make it easy to run SQL in cells in your Jupyter Notebook as is without any Python code.  This notebook shows how to enable this feature in Cloud Pak for Data.  Using these examples would probably allow you to use them in Watson Studio outside of CPD as well.  I only show some basic Magic Commands here.  For more information on Db2 Magic Commands and lots of example see https://github.com/IBM/db2-jupyter/

<h2 id="pandas">Get the db2 magic commands notebook from github: <code>db2.ipynb</code></h2>

You must get and run the db2.iyndb notebook before using the magic commands.  You can't run the db2.ipynb notebook from the directory shown above.  Instead you need to reference the "raw" version as is done in the command below.  I got that raw URL by going into directory shown in the above "About" description, then clicking on the db2.ipynb link, and then clicking the "Raw" button near that top of the notebook itself.  Finally I copied the URL in the browser and pasted it in the wget command.

In [25]:
!wget https://raw.githubusercontent.com/IBM/db2-jupyter/master/db2.ipynb

--2020-03-02 16:30:39--  https://raw.githubusercontent.com/IBM/db2-jupyter/master/db2.ipynb
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.32.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.32.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 151979 (148K) [text/plain]
Saving to: 'db2.ipynb.1'

100%[======================================>] 151,979     --.-K/s   in 0.03s

2020-03-02 16:30:39 (4.52 MB/s) - 'db2.ipynb.1' saved [151979/151979]

### Run the db2 magic comands notebook

In [26]:
%run db2.ipynb

Db2 Extensions Loaded.

### Connect to Db2 Database
Change the connect string to use your own database, user, password, host and port

In [27]:
%sql CONNECT TO bludb USER user1013 USING ppppppp HOST host.or.ip PORT 50000;

Connection successful.

##### Run a query, putting the output into a list called db2indexes_list
Query the syscat.indexes view in the Db2 database.  Any view or table could be queried this way.  The magic command puts the data into a list datatype.  The row count, column count, data type and the view data are displayed.

In [28]:
db2indexs_list = %sql -r select * from syscat.indexes 
nbr_cols = len(db2indexs_list) - 1
print('ROW COUNT', len(db2indexs_list))
print('COLUMN COUNT',len(db2indexs_list[0]))
print(type(db2indexs_list))
print(db2indexs_list[0:3])

ROW COUNT 743
COLUMN COUNT 72
<class 'list'>
[['INDSCHEMA', 'INDNAME', 'OWNER', 'OWNERTYPE', 'TABSCHEMA', 'TABNAME', 'COLNAMES', 'UNIQUERULE', 'MADE_UNIQUE', 'COLCOUNT', 'UNIQUE_COLCOUNT', 'INDEXTYPE', 'ENTRYTYPE', 'PCTFREE', 'IID', 'NLEAF', 'NLEVELS', 'FIRSTKEYCARD', 'FIRST2KEYCARD', 'FIRST3KEYCARD', 'FIRST4KEYCARD', 'FULLKEYCARD', 'CLUSTERRATIO', 'CLUSTERFACTOR', 'SEQUENTIAL_PAGES', 'DENSITY', 'USER_DEFINED', 'SYSTEM_REQUIRED', 'CREATE_TIME', 'STATS_TIME', 'PAGE_FETCH_PAIRS', 'MINPCTUSED', 'REVERSE_SCANS', 'INTERNAL_FORMAT', 'COMPRESSION', 'IESCHEMA', 'IENAME', 'IEARGUMENTS', 'INDEX_OBJECTID', 'NUMRIDS', 'NUMRIDS_DELETED', 'NUM_EMPTY_LEAFS', 'AVERAGE_RANDOM_FETCH_PAGES', 'AVERAGE_RANDOM_PAGES', 'AVERAGE_SEQUENCE_GAP', 'AVERAGE_SEQUENCE_FETCH_GAP', 'AVERAGE_SEQUENCE_PAGES', 'AVERAGE_SEQUENCE_FETCH_PAGES', 'TBSPACEID', 'LEVEL2PCTFREE', 'PAGESPLIT', 'AVGPARTITION_CLUSTERRATIO', 'AVGPARTITION_CLUSTERFACTOR', 'AVGPARTITION_PAGE_FETCH_PAIRS', 'PCTPAGESSAVED', 'DATAPARTITION_CLUSTERFACTOR', 'INDCARD', 'AVGLEAFKEYSIZE', 'AVGNLEAFKEYSIZE', 'OS_PTR_SIZE', 'COLLECTSTATISTCS', 'DEFINER', 'LASTUSED', 'PERIODNAME', 'PERIODPOLICY', 'MADE_WITHOUTOVERLAPS', 'ENVSTRINGUNITS', 'NULLKEYS', 'FUNC_PATH', 'VIEWSCHEMA', 'VIEWNAME', 'REMARKS'], ['SYSIBM  ', 'INDTABLES01', 'SYSIBM  ', 'S', 'SYSIBM  ', 'SYSTABLES', '+CREATOR+NAME', 'U', 'N', 2, 2, 'REG ', ' ', -1, 1, 2, 2, 17, 775, -1, -1, 775, 95, -1.0, 0, 0, 0, 0, '2019-11-14 19:11:20.907790', '2020-03-02 03:16:17.858709', '', 0, 'N', 2, 'N', None, None, None, 5, 804, 29, 0, -1.0, 2.0, 0.0, -1.0, 0.0, -1.0, 0, -1, 'S', -1, -1.0, '', 0, 1.0, 775, 25, 25, 64, ' ', 'SYSIBM  ', '2020-03-02', None, 'N', 'N', 'SYSTEM', 'Y', None, None, None, None], ['SYSIBM  ', 'INDTABLES02', 'SYSIBM  ', 'S', 'SYSIBM  ', 'SYSTABLES', '+TBSPACE', 'D', 'N', 1, -1, 'REG ', ' ', -1, 2, 1, 1, 6, -1, -1, -1, 6, 98, -1.0, 0, 0, 0, 0, '2019-11-14 19:11:20.907790', '2020-03-02 03:16:17.858709', '', 0, 'N', 2, 'N', None, None, None, 5, 852, 77, 0, -1.0, 1.0, 0.0, -1.0, 0.0, -1.0, 0, -1, 'S', -1, -1.0, '', 0, 1.0, 775, 8, 8, 64, ' ', 'SYSIBM  ', '0001-01-01', None, 'N', 'N', 'SYSTEM', 'Y', None, None, None, None]]

##### Copy thge list to a data frame.

In [29]:
import pandas as pd
db2indexes_df = pd.DataFrame(db2indexs_list)
print(db2indexes_df.shape)
db2indexes_df.head()

(743, 72)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71
0,INDSCHEMA,INDNAME,OWNER,OWNERTYPE,TABSCHEMA,TABNAME,COLNAMES,UNIQUERULE,MADE_UNIQUE,COLCOUNT,UNIQUE_COLCOUNT,INDEXTYPE,ENTRYTYPE,PCTFREE,IID,NLEAF,NLEVELS,FIRSTKEYCARD,FIRST2KEYCARD,FIRST3KEYCARD,FIRST4KEYCARD,FULLKEYCARD,CLUSTERRATIO,CLUSTERFACTOR,SEQUENTIAL_PAGES,DENSITY,USER_DEFINED,SYSTEM_REQUIRED,CREATE_TIME,STATS_TIME,PAGE_FETCH_PAIRS,MINPCTUSED,REVERSE_SCANS,INTERNAL_FORMAT,COMPRESSION,IESCHEMA,IENAME,IEARGUMENTS,INDEX_OBJECTID,NUMRIDS,NUMRIDS_DELETED,NUM_EMPTY_LEAFS,AVERAGE_RANDOM_FETCH_PAGES,AVERAGE_RANDOM_PAGES,AVERAGE_SEQUENCE_GAP,AVERAGE_SEQUENCE_FETCH_GAP,AVERAGE_SEQUENCE_PAGES,AVERAGE_SEQUENCE_FETCH_PAGES,TBSPACEID,LEVEL2PCTFREE,PAGESPLIT,AVGPARTITION_CLUSTERRATIO,AVGPARTITION_CLUSTERFACTOR,AVGPARTITION_PAGE_FETCH_PAIRS,PCTPAGESSAVED,DATAPARTITION_CLUSTERFACTOR,INDCARD,AVGLEAFKEYSIZE,AVGNLEAFKEYSIZE,OS_PTR_SIZE,COLLECTSTATISTCS,DEFINER,LASTUSED,PERIODNAME,PERIODPOLICY,MADE_WITHOUTOVERLAPS,ENVSTRINGUNITS,NULLKEYS,FUNC_PATH,VIEWSCHEMA,VIEWNAME,REMARKS
1,SYSIBM,INDTABLES01,SYSIBM,S,SYSIBM,SYSTABLES,+CREATOR+NAME,U,N,2,2,REG,,-1,1,2,2,17,775,-1,-1,775,95,-1,0,0,0,0,2019-11-14 19:11:20.907790,2020-03-02 03:16:17.858709,,0,N,2,N,None,None,None,5,804,29,0,-1,2,0,-1,0,-1,0,-1,S,-1,-1,,0,1,775,25,25,64,,SYSIBM,2020-03-02,None,N,N,SYSTEM,Y,None,None,None,None
2,SYSIBM,INDTABLES02,SYSIBM,S,SYSIBM,SYSTABLES,+TBSPACE,D,N,1,-1,REG,,-1,2,1,1,6,-1,-1,-1,6,98,-1,0,0,0,0,2019-11-14 19:11:20.907790,2020-03-02 03:16:17.858709,,0,N,2,N,None,None,None,5,852,77,0,-1,1,0,-1,0,-1,0,-1,S,-1,-1,,0,1,775,8,8,64,,SYSIBM,0001-01-01,None,N,N,SYSTEM,Y,None,None,None,None
3,SYSIBM,INDTABLES03,SYSIBM,S,SYSIBM,SYSTABLES,+INDEX_TBSPACE,D,N,1,-1,REG,,-1,3,1,1,1,-1,-1,-1,1,100,-1,0,0,0,0,2019-11-14 19:11:20.907790,2020-03-02 03:16:17.858709,,0,N,2,N,None,None,None,5,852,77,0,-1,1,0,-1,0,-1,0,-1,S,-1,-1,,0,1,775,0,0,64,,SYSIBM,0001-01-01,None,N,N,SYSTEM,Y,None,None,None,None
4,SYSIBM,INDTABLES04,SYSIBM,S,SYSIBM,SYSTABLES,+LONG_TBSPACE,D,N,1,-1,REG,,-1,4,1,1,1,-1,-1,-1,1,100,-1,0,0,0,0,2019-11-14 19:11:20.907790,2020-03-02 03:16:17.858709,,0,N,2,N,None,None,None,5,852,77,0,-1,1,0,-1,0,-1,0,-1,S,-1,-1,,0,1,775,0,0,64,,SYSIBM,0001-01-01,None,N,N,SYSTEM,Y,None,None,None,None

### You can have more complex queries if desired
Also its always a good idea to get just the columns you need in your query and thus your data frame.  Use the back slash to continue the query on a new line.

In [30]:
db2indexs_list = %sql -r select indname, tabname, tabschema, uniquerule, colcount, \
                                pctfree, nlevels, stats_time, compression \
                           from syscat.indexes \
                          where TABSCHEMA not like 'SYS%' \
                            and TABSCHEMA not like 'IBM%' 
nbr_cols = len(db2indexs_list) - 1
print('ROW COUNT', len(db2indexs_list))
print('COLUMN COUNT',len(db2indexs_list[0]))
print(type(db2indexs_list))
db2indexes_df = pd.DataFrame(db2indexs_list)
print(db2indexes_df.shape)
db2indexes_df.head()

ROW COUNT 65
COLUMN COUNT 9
<class 'list'>
(65, 9)

,0,1,2,3,4,5,6,7,8
0,INDNAME,TABNAME,TABSCHEMA,UNIQUERULE,COLCOUNT,PCTFREE,NLEVELS,STATS_TIME,COMPRESSION
1,SQL191215185042622707,CUSTOMER_DEMOGRAPHICS,DFD,D,2,0,1,2019-12-15 18:50:46.545753,Y
2,SQL191215185117765229,CUSTOMER_CHURN,DFD,D,2,0,1,2019-12-15 18:51:20.166780,Y
3,SQL191215185245683482,MERGED_DEMOGRAPHICS_TRADING_CUSTOMER,CPD,D,2,0,1,2019-12-15 18:52:48.293380,Y
4,SQL191215185332076952,CUSTOMER_OFFER_ACCEPTED,CPD,D,2,0,1,2019-12-15 18:53:35.401269,Y

 Disconnect from the database when you are done.

In [31]:
%sql connect reset;

Connection successful.